name: Android Check Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: "Build APK"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew assembleProdNoiAppRelease

    - name: Upload APK
      uses: actions/upload-artifact@v1.0.0
      with:
          name: app
          path: app/build/outputs/apk/prodNoiApp/release/app-prodNoiApp-release.apk

    - name: Build Debug with Gradle
      run: ./gradlew assembleDevNoiAppDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v1.0.0
      with:
          name: app
          path: app/build/outputs/apk/devNoiApp/debug/app-devNoiApp-debug.apk
